# Generated by Django 3.0.6 on 2020-07-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='about_me',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
